### PR TITLE
LPS-72729 Create an exclusion rule for this case

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Hi @robertoDiaz , 
this fixes the issue on master. It uses some code that is not yet on ee-7.0.x, so I'll start to work to apply this change on ee-7.0.x.

Thank you!

**Comment by robertoDiaz** [comment]
Hey @linolaoj,

This code needs to be tested in integration cases, so please, if possible, resend it to me with this test.

If you have any doubts or if you need helpl, please tell me.

**Comment by linolaoj** [comment]
Ok, I'll add an integration test and send it back.
Thanks!

**Comment by linolaoj** [comment]
Pull request submitted to https://github.com/robertoDiaz/liferay-portal/pull/563. [See changes here.](https://github.com/linolaoj/liferay-portal/compare/6195920~1...6195920) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
