### PR TITLE
[TS|Master] LPS-127758 using admin user to check if form was published

### PR DESCRIPTION
**Pull request by rijema**
Click [here](https://issues.liferay.com/browse/LPS-127758) to see the LPS

Results:
The guest user is now able to see the content before publish to live. 
Tested on Google Chrome.

D236276A-D6FA-49D4-A84D-83112D4A231F

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Hi @rijema , 
can you please use RoleLocalService and UserLocalService instead of RoleLocalServiceUtil and UserLocalServiceUtil?

Thanks!

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
Hi @linolaoj, here it is. Thx.

**Comment by rijema** [comment]
ci:reevaluate:1127401_4495

**Comment by linolaoj** [comment]
@rijema, thank you for the update, test are failing because DDMFormDisplayContextTest.java also needs to be updated.

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Forwarded to https://github.com/liferay-forms/liferay-portal/pull/171
Thanks!

**Pull request closed without merging**
