### PR TITLE
LPS-74207 Use new method to pass more precise information about path from ServiceBuilder to ToolsUtil

### PR DESCRIPTION
**Pull request by cleydyr**
https://issues.liferay.com/browse/LPS-74207

### CODE REVIEW

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
ci:reopen

**Comment by linolaoj** [comment]
ci:retest

**Comment by cleydyr** [comment]
Sweet! Lino, can you please forward it to BChan?

Thanks

**Comment by linolaoj** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51487. [See changes here.](https://github.com/linolaoj/liferay-portal/compare/9da3500~1...9da3500) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51491. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
