### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests tomcat 9

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
hey @vicnate5 , do you think we can cover this with the change field type test? Thanks!

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57196. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
