### PR TITLE
LPS-70900 adding check for downloadURL, categories and tag

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by arboliveira** [comment]
Submitted as https://github.com/arboliveira/liferay-portal/pull/248

**Pull request closed without merging**
