### PR TITLE
WIPP

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
@clovisdasilvaneto Hey man, can you please rebase this one and send to me? Thanks :)

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Hi, @linolaoj. I sent you the rebased PR here(https://github.com/linolaoj/liferay-portal/pull/165)

**Pull request closed without merging**
