### PR TITLE
LPS-88242 Change upload icon

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69355. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
