### PR TITLE
LPD-27497

### PR DESCRIPTION
**Pull request by linolaoj**
- **LPD-27497 Picklist entries should allow capital letter on its key values**
- **LPD-27497 Assert picklist table integrity**
- **LPD-27497 Evaluating cases when formatting a string on Picklists**
- **LPD-27497 Link input field to a label element**
- **LPD-27497 Maintain capital letters on Picklists items for Poshi tests**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:objects

**Comment by linolaoj** [comment]
ci:test:help

**Comment by linolaoj** [comment]
ci:test:object

**Comment by rijema** [comment]
ci:test:report

**Comment by rijema** [comment]
ci:report:21637577

**Comment by rijema** [comment]
@linolaoj , I don't think the upgrade test is related to this failure. In fact, there is a picklist test failing, but it's trying to assert a content that does not exist. I didn't find where this test is called, but I believe that the execution is sequentially related to other tests, being necessary other tests running. The other picklists failing tests were already mapped as a test fix.

**Comment by linolaoj** [comment]
Hi @rijema , the tests of the modules/apps/object/object-test/src/testFunctional/tests/ObjectUpgrade.testcase should use data created on a previous version where the key names could be only lower case. So when it edits data it should look for the key starting with lower case and when it adds new data then it will default to the capital letter at the start. Can you please change it accordingly?

**Comment by linolaoj** [comment]
new pull request https://github.com/liferay-objects/liferay-portal/pull/3456

**Pull request closed without merging**
