### PR TITLE
LPS-70900 Search Result Summary test: added assertions for other root-dependent elements (Download URL, Tags)

### PR DESCRIPTION
**Pull request by arboliveira**
- Run test without the fix (https://github.com/linolaoj/liferay-portal/pull/65/commits/453ed554b51aca1ae14e3ad4d129ebf870816931)
- Notice test breaks when asserting the User (expected without the fix)
- Run test with the fix
- Notice test breaks earlier, when asserting the Download URL (or asserting the Tags.) See commit comment in https://github.com/linolaoj/liferay-portal/pull/65/commits/a9766670a3c34e8b6a57bc0ca89703cca010592b

### CODE REVIEW

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
ci:reopen

**Comment by linolaoj** [comment]
Pull request submitted to https://github.com/linolaoj/liferay-portal/pull/66. [See changes here.](https://github.com/linolaoj/liferay-portal/compare/e4081e1~2...e4081e1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Continued as https://github.com/linolaoj/liferay-portal/pull/65

**Pull request closed without merging**
