### PR TITLE
LPS-92334 | master

### PR DESCRIPTION
**Pull request by samanzanedo**

### CODE REVIEW

**Comment by samanzanedo** [comment]
References:
https://issues.liferay.com/browse/LPS-92334

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69801. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
