### PR TITLE
LPS-90984 renaming

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@linolaoj Can you please check if everything is working after my changes. If it's ok, please forward to BChan. Thanks!

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70099. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Pull request submitted to https://github.com/alexcandidos/liferay-portal/pull/15. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Pull request submitted to https://github.com/alexcandidos/liferay-portal/pull/16. [See changes here.](https://github.com/linolaoj/liferay-portal/compare/5ee82ea49224~1...5ee82ea49224) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
