### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests tomcat 9

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
@vicnate5 , can we cover this with the jump to page poshi tests? Thanks!

**Comment by vicnate5** [comment]
@pedroqueiroz https://issues.liferay.com/browse/LRQA-40171

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Ci:reopen

**Comment by linolaoj** [comment]
ci:reopen

**Comment by linolaoj** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57244. [See changes here.](https://github.com/linolaoj/liferay-portal/compare/eb44290~1...eb44290) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
ci:reopen

**Comment by pedroqueiroz** [comment]
Review done, just waiting for CI to be ok to run forms tests again.

**Comment by pedroqueiroz** [comment]
Resent at https://github.com/linolaoj/liferay-portal/pull/121.

**Pull request closed without merging**
