### PR TITLE
LPS-69107 portal-kernel version

### PR DESCRIPTION
**Pull request by marcellustavares**
@linolaoj, back end looks fine to me! thx we just need to think about a better solution to the front end.

There are currently two options to reuse our existing map taglib.

1. Extract out the liferay ui `custom_field` taglib
2. Use the dynamic_include as an extension point

I would rather to go with 1. Do you think it's doable? can you check this out?

cc @arboliveira @brunobasto

Thanks

### CODE REVIEW

**Comment by linolaoj** [comment]
I'll look into this.
Thank you @marcellustavares :)

**Comment by marcellustavares** [comment]
@linolaoj, if the option 1 is possible, please send it in a separate story.

thx

**Comment by marcellustavares** [comment]
@linolaoj, if the option 1 is possible, please send it in a separate story.

thx

**Comment by linolaoj** [comment]
Here it is https://github.com/marcellustavares/liferay-portal/pull/1751
Thanks!

**Pull request closed without merging**
