### PR TITLE
LPS-103678 SF

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@linolaoj tests were failing in https://github.com/leoadb/liferay-portal/pull/611. Please fix the tests and resend. Thanks!

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :)

**Comment by linolaoj** [comment]
new pull https://github.com/leoadb/liferay-portal/pull/615

**Pull request closed without merging**
