### PR TITLE
LPS-106890 Use iteration instead of filter

### PR DESCRIPTION
**Pull request by balazssk**
Hi @linolaoj

I've checked your suggestion and added single-quotes to the get method. And it works!
Thanks for suggesting iteration.

Can you please review?
https://issues.liferay.com/browse/LPS-106890

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Just started reviewing :)

**Comment by linolaoj** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/83394
Thanks!

**Pull request closed without merging**
