### PR TITLE
LPS-80362 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Please see regression in https://github.com/rafaprax/liferay-portal/pull/555#issuecomment-386364008

Here is the test fix

### CODE REVIEW

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
ci:test

**Comment by linolaoj** [comment]
@vicnate5, I could not reproduce the issue from the gif. So after ci is done I'll check again and forward if it is ok.
cc:@rafaprax
Thanks!

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
If `LocalFile.Forms#AddFormWithDuplicateTextFields` passes, then it is good, the test will catch the regression in the gif.

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Pull request submitted to https://github.com/linolaoj/liferay-portal/pull/124. [See changes here.](https://github.com/linolaoj/liferay-portal/compare/f7dcf64~1...f7dcf64) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
