### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests tomcat 9

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:reopen

**Comment by linolaoj** [comment]
ci:retest

**Comment by pedroqueiroz** [comment]
hey @vicnate5 , I think the errors are related to the pull :( Can you double check?

**Comment by vicnate5** [comment]
Yea. 2 unique failures.

1. Test fails to be able to select "User" condition
selectuserfail


2. Jump to Page rule breaks if user renames the page
pagetitlechange

**Comment by linolaoj** [comment]
Hi @pedroqueiroz , I'm closing this one as it needs to be rebased.

**Pull request closed without merging**
